version: "3.7"

services:
  
  web:
    build: .
    command: uwsgi --http :8000 --module repairs.wsgi

  
  nginx:
    build: ./nginx
    ports:
      - 8081:8080
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - web
