version: "3.7"

services:
  
  web:
    build: .
    command: uwsgi --http :8000 --module repairs.wsgi

  
  nginx:
    build:
      dockerfile: Dockerfile-nginx
    ports:
      - 80:8080
    depends_on:
      - web
