version: "3.7"

services:
  
  web:
    build: .
    command: uwsgi --http :8000 --module repairs.wsgi
    volumes:
      - .:/app
  
  nginx:
    build: ./nginx
    ports:
      - 8080:8080
    depends_on:
      - web
